global:
  # global.imageRegistry -- Globally override the image registry that is used. Can be overridden by specific containers. Defaults to quay.io
  imageRegistry: null
  # global.imagePullSecrets -- Globally add image pull secrets that are used.
  imagePullSecrets: []
image:
  # image.registry -- Registry containing the image for the Redirector
  registry:
  # image.repository -- Repository containing the image for the Redirector
  repository: stackstate/redirector
  # image.tag -- Tag of the image for the Redirector
  tag: v0.0.3
  # image.pullPolicy -- Pull policy for the image for the Redirector
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 25m
    memory: 32Mi
  requests:
    cpu: 25m
    memory: 32Mi
# tolerations -- Tolerations for the pods
tolerations: null
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
replicaCount: 2
ingress:
  enabled: false
  path: /
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/component
          operator: In
          values:
          - redirector
      topologyKey: kubernetes.io/hostname
