apiVersion: v2
appVersion: 3.0.2
version: 3.5.2
description: Helm chart for the StackState cluster agent.
keywords:
- aiops
- monitoring
- stackstate
home: https://github.com/StackVista/stackstate-agent
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
- name: Stackstate Ops Team
  email: ops@stackstate.com
name: stackstate-agent
