apiVersion: v2
description: A Helm chart for Sock Shop
name: sock-shop
version: 0.2.11
appVersion: 0.3.5
dependencies:
  - name: locust
    version: 0.31.1
    repository: https://charts.deliveryhero.io
    condition: locust.enabled
