apiVersion: v2
description: Official Elastic helm chart for Elasticsearch
home: https://github.com/elastic/helm-charts
name: elasticsearch
version: 8.19.4-stackstate.1
appVersion: 8.19.4
sources:
  - https://github.com/elastic/elasticsearch
icon: https://helm.elastic.co/icons/elasticsearch.png
maintainers:
  - name: SUSE Observability Ops Team
    email: suse-observability-ops@suse.com
dependencies:
  - name: prometheus-elasticsearch-exporter
    repository: file://../prometheus-elasticsearch-exporter
    version: "5.8.0-suse-observability.1"
    condition: prometheus-elasticsearch-exporter.enabled
