apiVersion: v2
description: Official Elastic helm chart for Elasticsearch
home: https://github.com/elastic/helm-charts
name: elasticsearch
version: 7.17.2-stackstate.4
appVersion: 7.17.2
sources:
  - https://github.com/elastic/elasticsearch
icon: https://helm.elastic.co/icons/elasticsearch.png
maintainers:
- name: Stackstate Ops Team
  email: ops@stackstate.com
dependencies:
  - name: prometheus-elasticsearch-exporter
    version: 4.13.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-elasticsearch-exporter.enabled
