apiVersion: v1
appVersion: 0.1.0
version: 0.2.8
description: AMI cleaner -- Clean old AWS AMI images.
keywords:
  - aiops
  - monitoring
  - stackstate
home: https://gitlab.com/stackvista/devops/helm-charts.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
name: aws-amicleaner
