{{- define "stackstate.problemProducer.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-problem-producer-log
data:
  logback.groovy: |
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "WARN" "AdditionalLogging" .Values.stackstate.components.problemProducer.additionalLogging) .) | nindent 4 -}}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateProblemProducerLogConfigMap := fromYaml (include "stackstate.problemProducer.configmap-log" .) -}}
{{- toYaml (merge $stackstateProblemProducerLogConfigMap $commonConfigMap) -}}
{{- end -}}
