{{ if .Values.clickhouse.enabled }}
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "suse-observability"
spec:
  defaults:
    templates:
      podTemplate: default-pod-template
      dataVolumeClaimTemplate: data-volumeclaim-template
  configuration:
    settings:
      # listen clickhosue-server embedded prometheus endpoint
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      prometheus/metrics: true
    users:
      observability/password: {{ .Values.clickhouse.auth.observability.password }}
      observability/networks/ip: "::/0"
      observability/grants/query:
        - "GRANT ALL ON otel.*"
        - "GRANT CLUSTER ON *.*"
      backup/password: {{ .Values.clickhouse.auth.backup.password }}
      backup/networks/ip: "::/0"
      backup/grants/query:
        - "GRANT ALL ON *.*"
    zookeeper:
      nodes:
        {{- range $zkHost := .Values.clickhouse.externalZookeeper.servers }}
        - host: {{ $zkHost }}
        {{- end }}
    clusters:
      - name: "default"
        layout:
          shardsCount: {{ .Values.clickhouse.shards }}
          replicasCount: {{ .Values.clickhouse.replicaCount }}

  templates:
    podTemplates:
      - name: default-pod-template
        spec:
          containers:
            - name: clickhouse
              metadata:
                annotations:
                  ad.stackstate.com/clickhouse.check_names: '["openmetrics"]'
                  ad.stackstate.com/clickhouse.init_configs: "[{}]"
                  ad.stackstate.com/clickhouse.instances: '[ { "prometheus_url": "http://%%host%%:9363/metrics", "namespace": "stackstate", "metrics": ["ClickHouseAsyncMetrics_*", "ClickHouseMetrics_*", "ClickHouseProfileEvents_*"] } ]'
                  ad.stackstate.com/clickhouse-backup.check_names: '["openmetrics"]'
                  ad.stackstate.com/clickhouse-backup.init_configs: "[{}]"
                  ad.stackstate.com/clickhouse-backup.instances: '[ { "prometheus_url": "http://%%host%%:7171/metrics", "namespace": "stackstate", "metrics": ["clickhouse_backup_*"] } ]'
                  checksum/stackstate-backup-config: "{{ toJson .Values.clickhouse | sha256sum }}"  # TODO hash config map instead of values
              image: {{ include "common.image" ( dict "image" .Values.clickhouse.image "context" $) }}
              {{- with .Values.clickhouse.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              ports:
                - name: "metrics"
                  containerPort: 9363
            {{ if .Values.clickhouse.backup.enabled }}
            - name: clickhouse-backup
              image: {{ include "common.image" ( dict "image" .Values.clickhouse.backup.image "context" $) }}
              command:
                - /app/entrypoint.sh
              env:
                - name: CLICKHOUSE_REPLICA_ID
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
              ports:
                - containerPort: 7171
                  name: backup-api
              {{- with .Values.clickhouse.backup.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - mountPath: /etc/clickhouse-backup.yaml
                  name: clickhouse-backup-config
                  subPath: config.yaml
                - mountPath: /app/entrypoint.sh
                  name: clickhouse-backup-scripts
                  subPath: backup_entrypoint.sh
            {{ end }}
          volumes:
            - name: clickhouse-backup-config
              configMap:
                name: suse-observability-clickhouse-backup
            - name: clickhouse-backup-scripts
              configMap:
                name: suse-observability-clickhouse-backup
                defaultMode: 0550
          securityContext:
            runAsUser: 1000
            fsGroup: 10000
            runAsGroup: 1000
          {{include "merge.affinity"  ( dict "affinity" .Values.clickhouse.affinity "context" $) | nindent 10 }}
    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          storageClassName: {{ .Values.clickhouse.persistence.data.storageClassName }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.persistence.data.size }}
  {{ end }}
