{{- $kubeStateOverridden := (include "stackstate-k8s-agent.nodeAgent.kube-state-metrics.overridden" $) }}
{{- $checksAgentKSM := and (and .Values.checksAgent.enabled (or .Values.dependencies.kubeStateMetrics.enabled .Values.checksAgent.kubeStateMetrics.url)) (not $kubeStateOverridden) }}
{{- if or .Values.nodeAgent.config.override $checksAgentKSM }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-node-agent
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: node-agent
data:
{{-  if $checksAgentKSM }}
  _etc_stackstate-agent_conf.d_kubernetes_state.d_auto_conf.yaml: |
{{- end }}
{{- range .Values.nodeAgent.config.override }}
  {{ .path | replace "/" "_"}}_{{ .name }}: |
{{ .data | indent 4 -}}
{{- end -}}
{{- end -}}
