#####################
# General variables #
#####################

# backoffLimit -- For failed jobs, how many times to retry.
backoffLimit: 3
# failedJobsHistoryLimit -- The number of failed CronJob executions that are saved.
failedJobsHistoryLimit: 5
# successfulJobsHistoryLimit -- The number of successful CronJob executions that are saved.
successfulJobsHistoryLimit: 5
# restartPolicy -- For failed jobs, how to handle restarts.
restartPolicy: OnFailure
# schedule -- Default schedule for this CronJob.
schedule: "*/10 * * * *"

extraEnv:
  # extraEnv.open -- Extra open environment variables to inject into pods.
  open: {}
  # extraEnv.secret -- Extra secret environment variables to inject into pods via a `Secret` object.
  secret: {}

image:
  # image.repository -- Base container image registry.
  repository: quay.io/stackstate/gitlab-steward
  # image.tag -- Default container image tag.
  tag: v0.5.0
  # image.pullPolicy -- Default container image pull policy.
  pullPolicy: Always
  # image.pullSecrets -- Extra secrets / credentials needed for container image registry. Is ignored when specifying a pullSecretUsername/password
  pullSecrets: []
  # image.pullSecretUsername -- Specify username and password to create an image pull secret that is used to pull the imagepullSecretUsername:
  pullSecretUsername:
  # image.pullSecretPassword -- Specify username and password to create an image pull secret that is used to pull the image
  pullsecretPassword:

# nameOverride -- Override the name of the chart.
nameOverride: ""
# fullnameOverride -- Override the fullname of the chart.
fullnameOverride: ""

resources:
  limits:
    # resources.limits.cpu -- CPU resource limits.
    cpu: "100m"
    # resources.limits.memory -- Memory resource limits.
    memory: "128Mi"
  requests:
    # resources.requests.cpu -- CPU resource requests.
    cpu: "100m"
    # resources.requests.memory -- Memory resource requests.
    memory: "128Mi"

serviceAccount:
  # serviceAccount.annotations -- Extra annotations for the `ServiceAccount` object.
  annotations: {}
  # serviceAccount.create -- Create the `ServiceAccount` object.
  create: true

# nodeSelector -- Node labels for pod assignment.
nodeSelector: {}

# tolerations -- Toleration labels for pod assignment.
tolerations: []

# affinity -- Affinity settings for pod assignment.
affinity: {}

# securityContext -- securityContext for the container.
securityContext:
  # securityContext.enabled -- Whether the securityContext should be set up for the container
  enabled: true
  # securityContext.enabled -- AllowPrivilegeEscalation controls whether a process can gain more
  #  privileges than its parent process
  allowPrivilegeEscalation: false
  # securityContext.runAsNonRoot -- Indicates that the container must run as a non-root user
  runAsNonRoot: true
  # securityContext.runAsUser The UID to run the entrypoint of the container process.
  runAsUser: 65534

########################
# StackState variables #
########################

steward:
  # steward.dryRun -- Show which environments *would be* stopped, but don't actually stop them.
  dryRun: "False"
  gitlab:
    # steward.gitlab.apiToken -- (string) **REQUIRED** The GitLab API token.
    apiToken:
  # steward.logLevel -- The logging level of the application; one of 'debug', 'info', or 'warning'
  logLevel: ""
  # steward.maxDuration -- Amount of time (in days) before an environment is stopped.
  maxDuration: 2
  # stackstateProject -- The StackState project to scan for environments.
  stackstateProject: stackstate
