{{- if .Values.secret.enabled -}}
{{- $passwordValue := (randAlphaNum 16) | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch.uname" . }}-credentials
  labels:
    {{- include "elasticsearch.labels.recommended" . | nindent 4 }}
    {{- include "elasticsearch.labels.common" . | nindent 4 }}
type: Opaque
data:
  username: {{ "elastic" | b64enc }}
  {{- if .Values.secret.password }}
  password: {{ .Values.secret.password | b64enc }}
  {{- else }}
  password: {{ $passwordValue }}
  {{- end }}
{{- end }}
