{{- if .Values.createCert }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "elasticsearch.uname" . }}-certs
  labels:
    {{- include "elasticsearch.labels.recommended" . | nindent 4 }}
    {{- include "elasticsearch.labels.common" . | nindent 4 }}
    heritage: {{ .Release.Service }}
data:
{{ ( include "elasticsearch.gen-certs" . ) | indent 2 }}
{{- end }}
