apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gitlab-steward.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gitlab-steward.labels" . | indent 4 }}
spec:
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/name: {{ include "gitlab-steward.name" . }}
        spec:
        {{- if .Values.image.pullSecretUsername }}
          imagePullSecrets:
          - name: {{ include "gitlab-steward.fullname" . }}-pull-secret
        {{- else -}}
          {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            {{ include "gitlab-steward.envVars" . | indent 12 }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            {{- if .Values.securityContext.enabled }}
            securityContext:
            {{- omit .Values.securityContext "enabled" | toYaml | nindent 14 }}
            {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          serviceAccountName: {{ include "gitlab-steward.fullname" . }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
