apiVersion: v2
appVersion: 2.17.1
version: 2.0.7
description: Helm chart for the StackState cluster agent.
keywords:
- aiops
- monitoring
- stackstate
home: https://github.com/StackVista/stackstate-agent
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
name: cluster-agent
dependencies:
- name: kube-state-metrics
  version: 2.2.5
  repository: https://charts.bitnami.com/bitnami
  condition: dependencies.kubeStateMetrics.enabled
