apiVersion: v2
appVersion: "1.0.0"
version: 1.0.0
description: Helm Chart for rendering StackState Values
keywords:
  - kubernetes
  - observability
  - stackstate
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Stackstate Ops Team
    email: ops@stackstate.com
name: stackstate-values
