# receiverApiKey -- The StackState Receiver API Key, used for sending telemetry data to StackState's Receiver API.
receiverApiKey: ""

# imageRegistry -- The registry to pull the StackState images from.
imageRegistry: "quay.io"

pullSecret:
  # pullSecret.username -- The username used for pulling all StackState images from the registry.
  username: ""
  # pullSecret.password -- The password used for pulling all StackState images from the registry.
  password: ""

# license -- The StackState license key.
license:

# baseUrl -- The base URL of the StackState instance.
baseUrl: ""

# adminApiPassword -- The password for the default 'admin' user used for authenticating with the StackState Admin API. If not provided a random password is generated. If the password is not a bcrypt hash, but provided in plaintext, the value will be bcrypt hashed in the output.
adminApiPassword: ""
# adminPassword -- The password for the default 'admin' user used for authenticating with the StackState UI. If not provided a random password is generated.  If the password is not a bcrypt hash, but provided in plaintext, the value will be bcrypt hashed in the output.
adminPassword: ""
