apiVersion: v2
appVersion: 2.5.4
version: 3.0.0
description: Trafficmirror -- mirror traffic to various endpoints.
keywords:
  - mirror
  - stackstate
  - traffic
  - trafficmirror
home: https://github.com/rb3ckers/trafficmirror
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
- name: Stackstate Ops Team
  email: ops@stackstate.com
name: trafficmirror
dependencies:
  - name: common
    version: "*"
    repository: file://../common/
