container:
  livenessProbeDefaults:
    # container.livenessProbeDefaults.enabled -- Use defaults for the `livenessProbe` from the upstream `common` chart.
    enabled: true
  readinessProbeDefaults:
    # container.readinessProbeDefaults.enabled -- Use defaults for the `readinessProbe` from the upstream `common` chart.
    enabled: true

image:
  # image.repository -- Base container image repository.
  repository: ghcr.io/rb3ckers/trafficmirror
  # image.tag -- Default container image tag.
  tag: v2.5.4

ingress:
  # ingress.enabled -- Enable use of ingress controllers.
  enabled: false

trafficmirror:
  # trafficmirror.mainUrl -- The default URL to receive the mirrored traffic.
  mainUrl: ""
  # trafficmirror.mirrorUrls -- The additional URLs that should also receive mirrored traffic.
  mirrorUrls: []
  # trafficmirror.password -- Basic auth password for the Trafficmirror service.
  password: ""
  # trafficmirror.username -- Basic auth username for the Trafficmirror service.
  username: ""
  # trafficmirror.failAfterMinutes -- Remove a target when it has been failing for this many minutes.
  failAfterMinutes: 30
  # trafficmirror.retryAfterMinutes -- After 5 successive failures a target is temporarily disabled, it will be retried after this many minutes.
  retryAfterMinutes: 1
  # trafficmirror.maxQueuedRequests -- Max requests that gets queued per mirror target.
  maxQueuedRequests: 500
  # trafficmirror.mainTargetDelayMs -- Delay executions to main target, this gives the mirror time to catch up, and increases parallelism.
  mainTargetDelayMs: 200
  # trafficmirror.enablePProf -- Enable pprof profiling
  enablePProf: false
deployment:
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
