{{- if include "stackstate-k8s-agent.processAgent.podCorrelation.remoteCache.enabled" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-remote-kube-cache
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: remote-kube-cache
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-remote-kube-cache
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: remote-kube-cache
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      # today we cannot customize the cache to just list pods, it lists by default also services and nodes.
      - "services"
      - "nodes"
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-remote-kube-cache
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: remote-kube-cache
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-remote-kube-cache
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-remote-kube-cache
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-remote-kube-cache
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: remote-kube-cache
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: remote-kube-cache
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "stackstate-k8s-agent.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: remote-kube-cache
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "stackstate-k8s-agent.name" . }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-remote-kube-cache
      containers:
        - name: remote-kube-cache
          image: docker.io/andreater/obi-k8s-cache:75fc78604a75baf80f95fac65c36590308da8e04 # todo!: we need to push this image somewhere.
          imagePullPolicy: Always
          env:
            # We can set all the config through environment variables https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/blob/2d5ea0eafeeebeaed7b4c21a997c5dbea2abe439/pkg/kubecache/config.go#L19
            - name: OTEL_EBPF_K8S_CACHE_LOG_LEVEL
              value: "info"
            - name: OTEL_EBPF_K8S_CACHE_PORT
              value: {{ include "stackstate-k8s-agent.remoteKubeCache.grpcPort" . | quote }}
            - name: OTEL_EBPF_K8S_CACHE_INTERNAL_METRICS_PROMETHEUS_PORT
              value: "8999"
          ports:
            - containerPort: {{ include "stackstate-k8s-agent.remoteKubeCache.grpcPort" . }}
              name: grpc
            - containerPort: 8999
              name: internalprom
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackstate-k8s-agent.remoteKubeCache.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: remote-kube-cache
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: remote-kube-cache
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "stackstate-k8s-agent.name" . }}
  ports:
    - name: grpc
      port: {{ include "stackstate-k8s-agent.remoteKubeCache.grpcPort" . }}
      protocol: TCP
    - name: internalprom
      port: 8999
      protocol: TCP
{{- end }}
