{{- define "hbase.console.container.main" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
name: console
image: "{{ include "common.image.registry" (dict "image" .Values.all.image "context" .) }}/{{ .Values.console.image.repository }}:{{ default (printf "%s-%s" .Values.version .Values.stackgraph.version) .Values.console.image.tag }}"
imagePullPolicy: {{ default .Values.stackgraph.image.pullPolicy .Values.console.image.pullPolicy | quote }}
args:
- /bin/bash
- -c
- while true; do sleep 10; done
env:
{{- include "all.commonEnv" . }}
{{- include "console.commonEnv" . }}
- name: ZOOKEEPER_QUORUM
{{- if eq .Values.deployment.mode "Distributed" }}
  value: {{ include "hbase.zookeeper.endpoint" . | quote }}
{{- else }}
  value: {{ template "common.fullname.short" . }}-stackgraph:2182
{{- end }}

{{- with .Values.console.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
securityContext:
  {{- $commonContainer.securityContext | toYaml | nindent 2 }}
workingDir: /tmp
{{- end -}}

{{- define "hbase.console.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "hbase.console.container.main" .) -}}
{{- $stackstateHbaseConsoleContainer := (merge $overrideContainer $commonContainer) }}
metadata:
  labels:
    app.kubernetes.io/component: console
{{- if .Values.global.commonLabels }}
{{- include "hbase.commonLabels" . | indent 4 }}
{{- end }}
  name: {{ template "common.fullname.short" . }}-console
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: console
{{- with .Values.console.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: console
{{- if .Values.global.commonLabels }}
{{- include "hbase.podLabels" . | indent 8 }}
{{- end }}
    spec:
      {{- include "common.image.pullSecret.name" (dict "images" (list .Values.all.image) "context" $) | nindent 6 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "common.fullname.short" . }}-console
      {{- end }}
      {{- if .Values.console.securityContext.enabled }}
      securityContext: {{- omit .Values.console.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - {{ toYaml $stackstateHbaseConsoleContainer | nindent 8 }}
    {{- if or .Values.all.nodeSelector .Values.console.nodeSelector }}
      nodeSelector:
      {{- with .Values.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.all.affinity .Values.console.affinity }}
      affinity:
      {{- with .Values.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.all.tolerations .Values.console.tolerations }}
      tolerations:
      {{- with .Values.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end -}}

{{- if .Values.console.enabled }}
{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $stackstateHbaseConsoleDeployment := fromYaml (include "hbase.console.deployment" .) -}}
{{- toYaml (mergeOverwrite $commonDeployment $stackstateHbaseConsoleDeployment) -}}
{{- end -}}
