apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "labels" . | nindent 4 }}
data:
  BASEURL: {{ include "baseUrl" . }}
  CLUSTER: {{ required  ".Values.cluster has to be set"  .Values.cluster }}
  STORAGE_PROVIDER: {{ required  ".Values.gcp.bucket has to be set" .Values.storageProvider }}
  {{ if eq .Values.storageProvider "gcp" -}}
  BUCKET: {{ required ".Values.gcp.bucket has to be set" .Values.gcp.bucket }}
  PROJECT: {{ required ".Values.gcp.project has to be set" .Values.gcp.project }}
  {{- else if eq .Values.storageProvider "aws" -}}
  BUCKET: {{ required ".Values.aws.bucket has to be set" .Values.aws.bucket }}
  REGION: {{ required ".Values.aws.region has to be set" .Values.aws.region }}
  {{- end }}
