apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "labels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount | int }}
{{- if eq .Values.storageProvider "local" }}
  strategy:
    type: Recreate
{{- end }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fullname" . }}
      {{- include "image-pull-secrets" . | nindent 6 }}
      containers:
      - name: falco-reporter
        image: "{{ include "image-registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "fullname" . }}
        - secretRef:
            name: {{ include "fullname" . }}
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if eq .Values.storageProvider "local" }}
        volumeMounts:
          - name: local
            mountPath: {{ .Values.local.directory }}
{{- end }}
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if eq .Values.storageProvider "local" }}
      volumes:
        - name: local
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}
{{- end }}
