{{- if eq .Values.storageProvider "local" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.local.persistent.accessMode }}
  resources:
    requests:
      storage: {{ .Values.local.persistent.storageSize }}
{{- end }}
