apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  SLACK_TOKEN: {{ .Values.slack.token | b64enc }}
