apiVersion: apps/v1
kind: Deployment
metadata:
  name: apacheds-deployment
spec:
  selector:
    matchLabels:
      app: apacheds
  template:
    metadata:
      labels:
        app: apacheds
    spec:
      containers:
      - name: apacheds
        image: stackstate/apacheds:1.2
        ports:
        - containerPort: 10389
          name: ldap
        - containerPort: 10636
          name: ldap-ssl
---
apiVersion: v1
kind: Service
metadata:
  name: sts-ldap
spec:
  type: ClusterIP
  selector:
    app: apacheds
  ports:
  - port: 10389
    name: ldap
  - port: 10636
    name: ldap-ssl
