apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-image-list-to-s3.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "k8s-image-list-to-s3.labels" . | indent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
