---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-image-list-to-s3.fullname" . }}
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-image-list-to-s3.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-image-list-to-s3.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-image-list-to-s3.fullname" . }}
  namespace: {{.Release.Namespace}}
