apiVersion: v1
kind: ServiceAccount
metadata:
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{ include "k8s-image-list-to-s3.labels" . | nindent 4 }}
  name: {{ include "k8s-image-list-to-s3.fullname" . }}
  namespace: {{ .Release.Namespace }}
