---
{{- if .Values.featureflags.demoScenarioSimulation.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: featureflags-failure-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: featureflags-failure-deployment
subjects:
  - kind: ServiceAccount
    name: featureflags-failure-deployment
    namespace: {{ .Release.Namespace }}
{{- end }}
