{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}
spec:
  {{- with .Values.resourceQuota.hard }}
  hard:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-default
spec:
  {{- with .Values.limitRange.default }}
  limits:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
