apiVersion: v1
appVersion: 0.1.0
version: 0.1.11
description: Iceman -- Export configuration for all StackState instances in a cluster to an S3 bucket as backup (i.e. freeze their configuration state).
keywords:
- aiops
- backup
- monitoring
- stackstate
home: https://gitlab.com/stackvista/devops/iceman.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
- name: Stackstate Ops Team
  email: ops@stackstate.com
name: iceman
