apiVersion: v1
appVersion: 0.0.1
version: 0.0.2
description: Get the list of the Docker images deployed to the K8s cluster and uploads it to S3 bucket
home: https://gitlab.com/stackvista/devops/helm-charts.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Stackstate Ops Team
    email: ops@stackstate.com
name: k8s-image-list-to-s3
