#####################
# General variables #
#####################

# backoffLimit -- For failed jobs, how many times to retry.
backoffLimit: 3
# failedJobsHistoryLimit -- The number of failed CronJob executions that are saved.
failedJobsHistoryLimit: 5
# successfulJobsHistoryLimit -- The number of successful CronJob executions that are saved.
successfulJobsHistoryLimit: 5
# restartPolicy -- For failed jobs, how to handle restarts.
restartPolicy: Never
# schedule -- Default schedule for this CronJob.
schedule: "0 1 * * *"

# podAnnotations -- Annotations for the `Job` pod.
podAnnotations: {}

image:
  # image.repository -- Base container image registry. Any image with kubectl, jq, aws-cli and gsutil will do.
  repository: quay.io/stackstate/sts-ci-images
  # image.tag -- Default container image tag.
  tag: stackstate-devops-9a5f8c3b
  # image.pullPolicy -- Default container image pull policy.
  pullPolicy: Always

# imagePullSecrets -- Extra secrets / credentials needed for container image registry.
imagePullSecrets: []
# nameOverride -- Override the name of the chart.
nameOverride: ""
# fullnameOverride -- Override the fullname of the chart.
fullnameOverride: ""

resources:
  limits:
    # resources.limits.cpu -- CPU resource limits.
    cpu: "100m"
    # resources.limits.memory -- Memory resource limits.
    memory: "128Mi"
  requests:
    # resources.requests.cpu -- CPU resource requests.
    cpu: "100m"
    # resources.requests.memory -- Memory resource requests.
    memory: "128Mi"

serviceAccount:
  # serviceAccount.annotations -- Extra annotations for the `ServiceAccount` object.
  annotations: {}

# nodeSelector -- Node labels for pod assignment.
nodeSelector: {}

# tolerations -- Toleration labels for pod assignment.
tolerations: []

# affinity -- Affinity settings for pod assignment.
affinity: {}

scan:
  # scan.ignoreNamespaceRegex -- Skip the namespaces whose names match the regex used by https://jqlang.github.io/jq/manual/#test
  ignoreNamespaceRegex: ""
  # scan.ignoreResourceNameRegex -- Skip the pods whose names match the regex used by https://jqlang.github.io/jq/manual/#test
  ignoreResourceNameRegex: ""

reports:
  aws:
    # reports.aws.enabled -- True if the reports should be stored to AWS S3 bucket
    enabled: true
    bucket:
      # reports.aws.bucket -- The name of the AWS S3 bucket to store reports
      name:
      # reports.aws.region -- The region of the AWS S3 bucket
      region:
      # reports.aws.prefix -- The prefix for the report files
      prefix: /
  gcp:
    # reports.gcp.enabled -- True if the reports should be stored to GCP Storage bucket. Ignored if `reports.aws.enabled` is true
    enabled: false
    bucket:
      # reports.gcp.bucket -- The name of the GCP Storage bucket to store reports
      name:
      # reports.gcp.prefix -- The prefix for the report files
      prefix: /
