apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "tenantmanager-labels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount | int }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "labels" . | nindent 8 }}
        {{- include "tenantmanager-labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fullname" . }}
      {{- include "image-pull-secrets" . | nindent 6 }}
      containers:
      - name: main
        image: "{{ include "image-registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/app/o11y-tooling", "tenantmanager", "--config", "/config/tenantmanager.yaml"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ include "fullname" . }}
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /config/tenantmanager.yaml
          subPath: tenantmanager.yaml
        - name: private-gpg-key
          mountPath: /config/private.key
          subPath: private.key
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "fullname" . }}
      - name: private-gpg-key
        secret:
          secretName: {{ include "fullname" . }}-gpg
