# Use with codecentric/keycloak helm chart

extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"

extraEnvFrom: |
  - secretRef:
      name: '{{ include "keycloak.fullname" . }}-admin'
secrets:
  admin:
    stringData:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'password'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/ingress.class: ingress-nginx-external
  rules:
    - host: auth-demo-keycloak.test.stackstate.io
      paths: [ '/' ]
  tls:
    - hosts:
        - auth-demo-keycloak.test.stackstate.io
      secretName: star-test-stackstate-io-ecc-tls
