apiVersion: v1
appVersion: v2.14.0
version: 0.2.7
description: AWS Nuke -- Clean an entire AWS account
keywords:
- aws
- stackstate
home: https://github.com/rebuy-de/aws-nuke
icon: https://images.ctfassets.net/pgltshdqevs3/6TJOSe8fbqeImQ24SSYmwa/4f3a418c1e133543aab8eb619850d9db/rebuy_logo.svg
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
name: aws-nuke
