{{- if .Values.ingress.enabled -}}
{{- $fullName := include "stackstate-standalone.fullname" . -}}
{{- $serviceAdminPort := .Values.service.admin.port -}}
{{- $serviceReceiverPort := .Values.service.receiver.port -}}
{{- $serviceUiPort := .Values.service.ui.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "stackstate-standalone.labels" . | indent 4 }}
  annotations:
    {{ include "gitlab.annotations" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{ $dot := . }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $dot.Values.ingress.path.ui }}?(.*)
            pathType: Prefix
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $serviceUiPort }}
          - path: {{ $dot.Values.ingress.path.admin }}/?(.*)
            pathType: Prefix
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $serviceAdminPort }}
          - path: {{ $dot.Values.ingress.path.receiver }}/?(.*)
            pathType: Prefix
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $serviceReceiverPort }}
    {{- end }}
  {{- end }}
{{- end }}
