receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: service_token_auth
        endpoint: ${env:MY_POD_IP}:4317
      http:
        auth:
          authenticator: service_token_auth
        endpoint: ${env:MY_POD_IP}:4318
connectors:
  stsservicegraph:
    latency_histogram_buckets: [2ms, 4ms, 6ms, 8ms, 10ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1s, 1400ms, 2s, 5s, 10s, 15s, 30s]
    dimensions:
      - service.namespace
      - service.instance.id
      - sts_api_key
      - peer.service
    store:
      ttl: 30s
      max_items: 50000
  forward:
  tracetotopo: {}
processors:
  stsusage: {}
  batch:
    timeout: 2s
    send_batch_size: 100000
  resource/addDefaultNamespace:
    attributes:
      - key: service.namespace
        action: insert
        value: default
  resource/addStsApiKey:
    attributes:
      - key: sts_api_key
        action: upsert
        from_context: auth.apiKey
  resource/removeStsApiKey:
    attributes:
      - key: sts_api_key
        action: delete
  attributes/removeStsApiKey:
    actions:
      - key: client_sts_api_key
        action: delete
      - key: server_sts_api_key
        action: delete
  # extension point to massage data so it conforms to the semantic conventions
  transform/semconv:
    error_mode: ignore
exporters:
  clickhousests:
    endpoint: tcp://suse-observability-clickhouse:9000?dial_timeout=10s&compress=lz4
    username: admin
    password: admin
    database: otel
    ttl: 72h
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    resources_table_name: otel_resources
    create_traces_table: false
    create_resources_table: false
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  prometheusremotewrite/victoria-metrics:
    endpoint: 'http://suse-observability-vmagent:8429/api/v1/write'
    resource_to_telemetry_conversion:
      enabled: true
  ststopology:
    endpoint: "${env:INTAKE_URL}"
  sts_kafka_exporter:
    brokers:
      - "suse-observability-kafka-headless:9092"
    topic: "sts-topology-stream"
    read_timeout: 2s
    produce_timeout: 5s
    required_acks: "leader"   # allowed: "none", "leader", "all"
    timeout: 30s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
extensions:
  service_token_auth:
    endpoint:
      url: "${env:API_URL}"
    cache:
      valid_size: 100
      valid_ttl: 5m
      invalid_size: 100
    schema: "SUSEObservability"
  # The health_check extension is mandatory for this chart.
  # Without the health_check extension the collector will fail the readiness and liveliness probes.
  # The health_check extension can be modified, but should never be removed.
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
  memory_ballast: {}
  sts_settings_provider:
    kafka:
      brokers:
        - "suse-observability-kafka-headless:9092"
      topic: "sts-internal-settings"
service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  extensions:
    - health_check
    - memory_ballast
    - service_token_auth
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - transform/semconv
        - resource/addDefaultNamespace
        - resource/addStsApiKey
        - batch
      exporters:
        - forward
        - stsservicegraph
        - tracetotopo
    traces/clickhouse:
      receivers:
        - forward
      processors:
        - stsusage
        - resource/removeStsApiKey
      exporters:
        - clickhousests
    metrics:
      receivers:
        - otlp
      processors:
        - resource/addDefaultNamespace
        - resource/addStsApiKey
        - batch
      exporters:
        - forward
    metrics/victoria-metrics:
      receivers:
        - forward
        - stsservicegraph
      processors:
        - resource/removeStsApiKey
        - attributes/removeStsApiKey
      exporters:
        - prometheusremotewrite/victoria-metrics
    metrics/topology:
      receivers:
        - forward
        - stsservicegraph
      exporters:
        - ststopology
    logs:
      receivers:
        - tracetotopo
      exporters:
        - sts_kafka_exporter
