{{- if .Values.baseConfig.generate }}
global:
  receiverApiKey: {{ template "sts.values.receiverKey" . }}
{{- if and .Values.pullSecret.username .Values.pullSecret.password }}
  imagePullSecrets:
    - suse-observability-pull-secret
{{- end }}

{{- if and .Values.pullSecret.username .Values.pullSecret.password }}
pull-secret:
  credentials:
    - password: {{ .Values.pullSecret.password | quote }}
      registry: {{ .Values.imageRegistry }}
      username: {{ .Values.pullSecret.username | quote }}
  enabled: true
  fullnameOverride: suse-observability-pull-secret
{{- end }}

stackstate:
  baseUrl: {{ .Values.baseUrl | required "Please provide your SUSE Observability base URL in 'baseUrl'" | quote }}
  admin:
    authentication:
      password: {{ template "sts.values.getOrGenerateAdminApiPassword" . }}
  authentication:
    adminPassword: {{ template "sts.values.getOrGenerateAdminPassword" . }}
  license:
    key: {{ .Values.license | required "Please provide your SUSE Observability license key in 'license'" | quote }}
---
{{ if .Values.generatedAdminPassword -}}
# Your SUSE Observability admin password is: {{ .Values.generatedAdminPassword }}
{{- end }}
{{ if .Values.generatedAdminApiPassword -}}
# Your SUSE Observability admin API password is: {{ .Values.generatedAdminApiPassword }}
{{- end }}
{{- end }}
