{{- if .Values.sizing.generate }}
  {{- $sizingProfile := .Values.sizing.profile | required "Please provide your SUSE Observability profile for sizing purposes"  }}
  {{- $sizing := .Files.Get (printf "profiles/%s.yaml" $sizingProfile) }}
  {{- if $sizing }}
  {{ $sizing }}
  {{- else }}
  {{- fail (printf "value for %s could not be found" $sizingProfile) }}
  {{- end }}
{{- end }}
