global:
  receiverApiKey: API_KEY
stackstate:
  license:
    key: 00000-00000-00000
  baseUrl: https://some-test-helm-render.stackstate.io
  authentication:
    adminPassword: test
  admin:
    authentication:
      password: test
ingress:
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/ingress.class: ingress-nginx-external
  enabled: true
  hosts:
    - host: some-test-helm-render.stackstate.io
  tls:
    - hosts:
        - some-test-helm-render.stackstate.io
      secretName: some-secret
hbase:
  hbase:
    master:
      metrics:
        servicemonitor:
          enabled: true
    regionserver:
      metrics:
        servicemonitor:
          enabled: true
  tephra:
    metrics:
      servicemonitor:
        enabled: true
networkPolicy:
  enabled: true

anomaly-detection:
  enabled: true
