global:
  # global.commonLabels -- Labels to apply to all resources
  commonLabels: {}

image:
  # image.registry -- Registry containing the image for the KafkaUp operator
  registry: quay.io
  # image.repository -- Repository containing the image for the KafkaUp operator
  repository: stackstate/kafkaup-operator
  # image.tag -- Tag of the image for the KafkaUp operator
  tag: 0.0.1
  # image.pullPolicy -- Pull policy for the image for the KafkaUp operator
  pullPolicy: IfNotPresent

kafkaSelectors:
  # kafkaSelectors.statefulSetName -- name of the statefulSet to operate on
  statefulSetName: "kafka"

  # kafkaSelectors.podLabel -- pod label of kafka pods to operate on
  podLabel:
    key: "app.kubernetes.io/component"
    value: "kafka"

# startVersion -- Version to use if no version is set. Allow going from a non-operated to operated situation
startVersion:

# nodeSelector:
#   node.kubernetes.io/purpose-core: "yes"

## Add labels to all the deployed resources
##
commonLabels: {}

## Add annotations to all the deployed resources
##
commonAnnotations: {}

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi

# strategy -- The strategy for the Deployment object.
strategy:
  type: RollingUpdate

securityContext:
  # securityContext.enabled -- Whether or not to enable the securityContext
  enabled: true
  # securityContext.fsGroup -- The GID (group ID) used to mount volumes
  fsGroup: 65534
  # securityContext.runAsGroup -- The GID (group ID) of the owning user of the process
  runAsGroup: 65534
  # securityContext.runAsNonRoot -- Ensure that the user is not root (!= 0)
  runAsNonRoot: true
  # securityContext.runAsUser -- The UID (user ID) of the owning user of the process
  runAsUser: 65534
