image:
  # image.registry -- Registry containing the image for the Helm reaper cron job
  registry: quay.io
  # image.repository -- Repository containing the image for the Helm reaper cron job
  repository: stackstate/sts-ci-images
  # image.tag -- Tag of the image for the Helm reaper cron job
  tag: stackstate-devops-0925b2ff
  # image.pullPolicy -- Pull policy for the image for the Helm reaper cron job
  pullPolicy: IfNotPresent
# nodeSelector -- Node labels for pod assignment.
nodeSelector: {}
# tolerations -- Toleration labels for pod assignment.
tolerations: []
# affinity -- Affinity settings for pod assignment.
affinity: {}
# schedule -- The cron schedule for the Helm reaper cron job.
schedule: "0 */1 * * *"
# reapNamespaceLabels -- The comma-separated list of the labels to filter namespaces to reap
reapNamespaceLabels: saas.stackstate.io/performance-test=true,saas.stackstate.io/branch-deployment=true
# reapNamespaceExcludeLabel -- The namespaces having this label will be ignored
reapNamespaceExcludeLabel: helm-reaper.stackstate.io/exclude=true
# Delete Helm charts that haven't been updated for the specified number of days.
deleteOlderThan: 3
resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi
