{{- if .Values.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: stackstate-cpu-alerts
  labels:
    app: kube-prometheus-stack
{{- with .Values.rules.additionalLabels }}
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  groups:
    - name: stackstate-cpu-alerts
      rules:
        - alert: StackStateContainerHighCpuUsage
          expr: sum(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~{{ .Values.rules.namespaceRegex | quote }},pod!~{{ .Values.rules.podNoCpuCheckRegex | quote }}}[15m])) by (namespace,pod,container) / sum(avg_over_time(kube_pod_container_resource_requests{namespace=~{{ .Values.rules.namespaceRegex | quote }},pod!~{{ .Values.rules.podNoCpuCheckRegex | quote }},resource="cpu"}[15m])) by (namespace,pod,container) * 100 > 200
          for: 15m
          labels:
            severity: warning
            alert_resource: {{` '{{ $labels.pod }}' `}}
          annotations:
            message: {{` 'The Average CPU usage for container ({{ $labels.pod }}/{{ $labels.container }}) exceeds CPU requests by more then 100%: {{ $value }}.'`}}
            runbook_url: https://www.notion.so/stackstate/Runbook-K8s-Stackstate-High-CPU-Usage-3b8862658fb34427bf992b6fcb8bcf85
{{- end }}
