apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8s-spot-termination-handler.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ template "k8s-spot-termination-handler.name" . }}
    helm.sh/chart: {{ template "k8s-spot-termination-handler.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if .Values.slackUrl }}
  SLACK_URL: {{ .Values.slackUrl | b64enc | quote }}
{{- end }}
{{- if .Values.gitlab.token }}
  GITLAB_TOKEN: {{ .Values.gitlab.token | b64enc | quote }}
{{- end }}
