apiVersion: v2
appVersion: "0.0.1"
version: 0.0.7
description: Helm chart for Opentelemetry Demo
keywords:
  - opentelemetry
  - kubernetes
  - observability
maintainers:
  - name: Stackstate Ops Team
    email: ops@stackstate.com
name: otel-demo
dependencies:
  - name: opentelemetry-demo
    version: 0.29.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
