global:
  # global.imageRegistry -- Globally override the image registry that is used. Can be overridden by specific containers. Defaults to quay.io
  imageRegistry: null
  # global.imagePullSecrets -- Globally add image pull secrets that are used.
  imagePullSecrets: []
image:
  # image.registry -- Registry containing the image for the Redirector
  registry:
  # image.repository -- Base container image registry. Any image with kubectl, jq, aws-cli and gsutil will do.
  repository: stackstate/falco-reporter
  # image.tag -- Default container image tag.
  tag: e3a0435d
  # image.pullPolicy -- Default container image pull policy.
  pullPolicy: IfNotPresent

# imagePullSecrets -- Extra secrets / credentials needed for container image registry.
imagePullSecrets: []
# nameOverride -- Override the name of the chart.
nameOverride: ""
# fullnameOverride -- Override the fullname of the chart.
fullnameOverride: ""

# replicaCount -- number of replicas to serve webhook
replicaCount: 1

resources:
  limits:
    # resources.limits.cpu -- CPU resource limits.
    cpu: "100m"
    # resources.limits.memory -- Memory resource limits.
    memory: "256Mi"
  requests:
    # resources.requests.cpu -- CPU resource requests.
    cpu: "100m"
    # resources.requests.memory -- Memory resource requests.
    memory: "256Mi"

serviceAccount:
  # serviceAccount.annotations -- Extra annotations for the `ServiceAccount` object.
  annotations: {}

# nodeSelector -- Node labels for pod assignment.
nodeSelector: {}

# tolerations -- Toleration labels for pod assignment.
tolerations: []

# affinity -- Affinity settings for pod assignment.
affinity: {}

securityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000

ingress:
  # ingress.enabled -- Whether to deploy Ingress resource.
  enabled: false
  # ingress.annotations - K8s annotations for the Ingress resource.
  annotations:
  # ingress.host -- HTTP host for the ingress.
  host:
  tls:
    # ingress.tls.enabled -- Whether to enable TLS for ingress.
    enabled: false
    # ingress.tls.secretName -- The name of K8s secrets containing SSL certificate for ingress.
    secretName:

slack:
  # slack.token -- Slack token to send message.
  token:
  # slack.channel -- Slack channel to send message to.
  channel:


# baseUrl -- Is used to build links in Slack reports. If not set ingress.host is used. If ingress.host is not set then the Kubernetes service is used.
baseUrl:

# storageProvider -- Where to save Falco reports: gcp, aws, or local.
storageProvider:

gcp:
  # gcp.bucket -- Google Cloud Storage bucket to store Falco reports.
  bucket:
  # gcp.bucket -- GCP project where the bucket resides.
  project:
aws:
  # aws.bucket -- AWS S3 bucket to store Falco reports.
  bucket:
  # aws.region -- AWS region where the bucket resides.
  region:
local:
  # local.directory -- The path to the local directory to store Falco reports.
  directory:
  persistent:
    # local.persistent.accessMode -- PV access mode.
    accessMode: ReadWriteOnce
    # local.persistent.storageSize -- PV size.
    storageSize: 1Gi
