ingress:
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/ingress.class: ingress-nginx-external
  enabled: true
  hosts:
    - host: auth-demo.test.stackstate.io
  tls:
    - hosts:
        - auth-demo.test.stackstate.io
      secretName: star-test-stackstate-io-ecc-tls
