{{- if .Values.clusterChecks.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-agent.fullname" . }}-clusterchecks
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: clusterchecks
{{- end -}}
{{- with .Values.clusterChecks.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
