{{- if .Values.clusterChecks.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "cluster-agent.fullname" . }}-clusterchecks
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: clusterchecks
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: clusterchecks
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "cluster-agent.name" . }}
{{- end -}}
