{{- define "cluster-agent.pull.secret" -}}
  {{- $fullName := include "cluster-agent.fullname" .context -}}
  {{- $registryAuthDocument := dict -}}
  {{- $_ := set $registryAuthDocument "username" .username }}
  {{- $_ := set $registryAuthDocument "password" .password }}
  {{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
  {{- $_ := set $registryAuthDocument "auth" $authMessage }}
  {{- $registryAuthMap := dict .registry $registryAuthDocument }}
  {{- $dockerAuthsDocuments := dict "auths" $registryAuthMap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-pull-secret
data:
  .dockerconfigjson: {{ $dockerAuthsDocuments | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}

{{- if .Values.all.image.pullSecretUsername }}
  {{ template "cluster-agent.pull.secret" (dict "username" .Values.all.image.pullSecretUsername "password" .Values.all.image.pullSecretPassword "registry" (include "cluster-agent.imageRegistry" $) "context" $) }}
{{- end }}
