apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-management.fullname" . }}
  labels:
    {{- include "tenant-management.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tenant-management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tenant-management.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if.Values.pullSecret.username }}
      imagePullSecrets:
       - name: tenant-management-pull-secret
      {{- end }}
      serviceAccountName: {{ include "tenant-management.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.app.db.url }}
            - name: DATABASE_USERNAME
              value: {{ .Values.app.db.username }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "tenant-management.fullname" . }}-db
                  key: password
            - name: SQS_PROVISIONING_QUEUE
              value: {{ .Values.app.sqs.provisioning_queue }}
            - name: SQS_PROVISIONING_STATUS_QUEUE
              value: {{ .Values.app.sqs.provisioning_status_queue }}
            - name: SQS_BILLING_QUEUE
              value: {{ .Values.app.sqs.billing_queue }}
            - name: SCALING_URL
              value: {{ .Values.app.scaling.url }}
            - name: SCALING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "tenant-management.fullname" . }}-scaling
                  key: api_key
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
{{/*              TODO add probes*/}}
{{/*          livenessProbe:*/}}
{{/*            {{- toYaml .Values.livenessProbe | nindent 12 }}*/}}
{{/*          readinessProbe:*/}}
{{/*            {{- toYaml .Values.readinessProbe | nindent 12 }}*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
