{{- define "pull.secret" -}}
  {{- $registryAuthDocument := dict -}}
  {{- $_ := set $registryAuthDocument "username" .username }}
  {{- $_ := set $registryAuthDocument "password" .password }}
  {{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
  {{- $_ := set $registryAuthDocument "auth" $authMessage }}
  {{- $registryAuthMap := dict .registry $registryAuthDocument }}
  {{- $dockerAuthsDocuments := dict "auths" $registryAuthMap }}
apiVersion: v1
kind: Secret
metadata:
  name: tenant-management-pull-secret
data:
  .dockerconfigjson: {{ $dockerAuthsDocuments | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}

{{- if.Values.pullSecret.username }}
  {{ template "pull.secret" (dict "username" .Values.pullSecret.username "password" .Values.pullSecret.password "registry" "quay.io" "context" $) }}
{{- end }}
