apiVersion: v2
appVersion: 4.7.0-snapshot.0
version: 1.1.13
description: Helm chart for Monitoring Dashboards
keywords:
  - monitoring
  - stackstate
  - prometheus
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Stackstate Ops Team
    email: ops@stackstate.com
name: stackstate-monitoring
