apiVersion: v2
appVersion: 2.19.1
version: 1.0.32
description: Helm chart for the StackState cluster agent.
keywords:
- monitoring
- stackstate
home: https://github.com/StackVista/stackstate-agent
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
- name: Stackstate Lupulus Team
  email: ops@stackstate.com
name: stackstate-k8s-agent
dependencies:
  - name: http-header-injector
    alias: http-header-injector-webhook
    # Local debugging: left here for future reference
    # repository: file:///home/bram/stackvista/agent/http-header-injector/charts/http-header-injector
    # version: "*"
    repository: https://helm-internal.stackstate.io
    version: 0.0.2
    # Warning: do not use this condition. this will not play well with the prehooks in the chart
    # condition: http-header-injector-webhook.enabled
