---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "notification-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "notification-operator.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "notification-operator.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
  issuerRef:
    kind: Issuer
    name: notification-operator-selfsigned-issuer
  secretName: {{ include  "notification-operator.webhook.secretName" . }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "notification-operator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
