apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "notification-operator.fullname" . }}-manager-role
  labels:
    {{- include "notification-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - saas.observability.suse.com
    resources:
      - notifications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - saas.observability.suse.com
    resources:
      - notifications/finalizers
    verbs:
      - update
  - apiGroups:
      - saas.observability.suse.com
    resources:
      - notifications/status
    verbs:
      - get
      - patch
      - update
