apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "notification-operator.fullname" . }}-editor-role
  labels:
    {{- include "notification-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - saas.observability.suse.com
    resources:
      - notifications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - saas.observability.suse.com
    resources:
      - notifications/status
    verbs:
      - get
