apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "notification-operator.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "notification-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "notification-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "notification-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
