apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-operator.fullname" . }}-manager-metrics-service
  labels:
    {{- include "notification-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    {{- include "notification-operator.selectorLabels" . | nindent 4 }}
