apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname.short" . }}
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/component: redirector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: redirector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: redirector
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: redirector
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redirector
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: redirector
    spec:
      {{- include "image-pull-secrets" . | nindent 6 }}
      containers:
      - name: redirector
        image: "{{ include "image-registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "fullname.short" . }}-config
