apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname.short" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redirector-labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    {{- include "redirector-labels" . | nindent 4 }}
