{{- define "trafficmirror.deployment.container" -}}
args:
{{- if .Values.trafficmirror.mainUrl }}
  - "--main"
  - {{ .Values.trafficmirror.mainUrl | quote }}
{{- end }}
{{- if .Values.trafficmirror.mirrorUrls }}
  {{- range .Values.trafficmirror.mirrorUrls }}
  - "--mirror"
  - {{ . | quote }}
  {{- end }}
{{- end }}
  - "--fail-after"
  - {{ .Values.trafficmirror.failAfterMinutes | quote }}
  - "--retry-after"
  - {{ .Values.trafficmirror.retryAfterMinutes | quote }}
  - "--max-queued-requests"
  - {{ .Values.trafficmirror.maxQueuedRequests | quote }}
  - "--main-target-delay-ms"
  - {{ .Values.trafficmirror.mainTargetDelayMs | quote }}
env:
- name: TRAFFICMIRROR_USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}
      key: username
- name: TRAFFICMIRROR_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}
      key: password
ports:
- containerPort: 8080
  name: app
livenessProbe:
  tcpSocket:
    port: app
readinessProbe:
  tcpSocket:
    port: app
{{- end -}}

{{- define "trafficmirror.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "trafficmirror.deployment.container" .) -}}
{{- $trafficmirrorContainer := (merge $overrideContainer $commonContainer) }}
spec:
  template:
    spec:
      containers:
      - {{ toYaml $trafficmirrorContainer | nindent 8 }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $trafficmirrorDeployment := fromYaml (include "trafficmirror.deployment" .) -}}
{{- toYaml (merge $trafficmirrorDeployment $commonDeployment) -}}
