{{- define "stackstate.k8s.authorization.instance.observer.rolebinding" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname.short" . }}-instance-observer
roleRef:
  kind: Role
  name: {{ template "common.fullname.short" . }}-instance-observer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: {{ template "common.fullname.short" . }}-instance-observer
{{- end -}}

{{- if (index .Values.stackstate.experimental "role-k8s-authz")  -}}
{{- include "stackstate.k8s.authorization.instance.observer.rolebinding" . -}}
{{- end -}}
