{{- define "stackstate.k8s.authorization.instance.base.rolebinding" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname.short" . }}-instance-base
roleRef:
  kind: Role
  name: {{ template "common.fullname.short" . }}-instance-base
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: {{ (index .Values "role-k8s-authz" "authprovider") }}{{ template "common.fullname.short" . }}-instance-guest
{{- end -}}

{{- if (index .Values "role-k8s-authz" "enabled")  -}}
{{- include "stackstate.k8s.authorization.instance.base.rolebinding" . -}}
{{- end -}}
