{{- define "stackstate.k8s.authorization.instance.troubleshooter.rolebinding" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname.short" . }}-instance-troubleshooter
roleRef:
  kind: Role
  name: {{ template "common.fullname.short" . }}-instance-troubleshooter
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: {{ template "common.fullname.short" . }}-instance-troubleshooter
{{- end -}}

{{- if (index .Values.stackstate.experimental "role-k8s-authz")  -}}
{{- include "stackstate.k8s.authorization.instance.troubleshooter.rolebinding" . -}}
{{- end -}}
