{{- define "stackstate.k8s.authorization.instance.recommended.rolebinding" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname.short" . }}-instance-recommended-access
roleRef:
  kind: Role
  name: {{ template "common.fullname.short" . }}-instance-recommended-access
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: "system:authenticated"
{{- end -}}

{{- if (include "suse-observability.features.enabled" (dict "key" "role-k8s-authz" "context" .)) -}}
{{- include "stackstate.k8s.authorization.instance.recommended.rolebinding" . -}}
{{- end -}}
