apiVersion: v1
appVersion: 1.15.0
version: 0.4.18
description: Helm chart for StackState standlone -- all components running inside a single container.
keywords:
  - aiops
  - monitoring
  - stackstate
home: https://gitlab.com/stackvista/devops/helm-charts.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
name: stackstate-standalone
