apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artifactory-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "artifactory-cleaner.labels" . | indent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}

  retentions.json: |
{{ .Values.retentionPolicies | toPrettyJson | indent 4 }}
