apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "artifactory-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "artifactory-cleaner.labels" . | indent 4 }}
spec:
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/name: {{ include "artifactory-cleaner.name" . }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ['bash', '/scripts/artifactory-cleaner.sh', '--apply']
            env:
              {{- include "artifactory-cleaner.env-vars" . | nindent 14 }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            volumeMounts:
            - name: scripts
              mountPath: /scripts
          volumes:
          - name: scripts
            configMap:
              name: {{ include "artifactory-cleaner.fullname" . }}
          restartPolicy: {{ .Values.restartPolicy }}
          serviceAccountName: {{ include "artifactory-cleaner.fullname" . }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          securityContext:
            fsGroup: 1000
            runAsUser: 1000
