apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifactory-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "artifactory-cleaner.labels" . | indent 4 }}
data:
  ARTIFACTORY_PASSWORD: {{ .Values.artifactory.password | b64enc }}
