{{- define "stackstate.receiver.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-receiver-log
data:
  logback.groovy: |
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "WARN" "AdditionalLogging" .Values.stackstate.components.receiver.additionalLogging) .) | nindent 4 -}}
{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateReceiverLogConfigMap := fromYaml (include "stackstate.receiver.configmap-log" .) -}}
{{- toYaml (merge $stackstateReceiverLogConfigMap $commonConfigMap) -}}
