{{- define "stackstate.viewHealth.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-view-health-log
data:
  logback.groovy: |
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "WARN" "AdditionalLogging" .Values.stackstate.components.viewHealth.additionalLogging) .) | nindent 4 -}}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateViewHealthLogConfigMap := fromYaml (include "stackstate.viewHealth.configmap-log" .) -}}
{{- toYaml (merge $stackstateViewHealthLogConfigMap $commonConfigMap) -}}
{{- end -}}
