{{- define "stackstate.correlate.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-correlate-log
data:
  logback.groovy: |
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "INFO" "AdditionalLogging" .Values.stackstate.components.correlate.additionalLogging) .) | nindent 4 -}}
{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateCorrelateLogConfigMap := fromYaml (include "stackstate.correlate.configmap-log" .) -}}
{{- toYaml (merge $stackstateCorrelateLogConfigMap $commonConfigMap) -}}
