{{- define "stackstate.healthSync.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-health-sync-log
data:
  logback.groovy: |
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "WARN" "AdditionalLogging" .Values.stackstate.components.healthSync.additionalLogging) .) | nindent 4 -}}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateHealthSyncLogConfigMap := fromYaml (include "stackstate.healthSync.configmap-log" .) -}}
{{- toYaml (merge $stackstateHealthSyncLogConfigMap $commonConfigMap) -}}
{{- end -}}
