{{- define "stackstate.trace2es.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-trace2es-log
data:
  logback.groovy: |
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "INFO" "AdditionalLogging" .Values.stackstate.components.trace2es.additionalLogging) .) | nindent 4 -}}
{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateK2ESLogConfigMap := fromYaml (include "stackstate.trace2es.configmap-log" .) -}}
{{- toYaml (merge $stackstateK2ESLogConfigMap $commonConfigMap) -}}
