{{- define "stackstate.router.deployment.container.main" -}}
name: router
image: "{{ include "stackstate.router.image.registry" . }}/{{ .Values.stackstate.components.router.image.repository }}:{{ .Values.stackstate.components.router.image.tag }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.router.image.pullPolicy | quote }}
env:
{{- include "stackstate.common.envvars" . }}
{{- include "stackstate.router.envvars" . }}
ports:
- containerPort: 8080
  name: router
- containerPort: 8001
  name: admin
livenessProbe:
  httpGet:
    path: /ready
    port: admin
  initialDelaySeconds: 5
readinessProbe:
  httpGet:
    path: /ready
    port: admin
  initialDelaySeconds: 5
{{- with .Values.stackstate.components.router.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
- mountPath: /etc/envoy
  name: config
{{- end -}}

{{- define "stackstate.router.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.router.deployment.container.main" .) -}}
{{- $stsstackstateRouterMainContainer := (merge $overrideContainer $commonContainer) -}}
metadata:
  name: {{ template "common.fullname.short" . }}-router
  labels:
    app.kubernetes.io/component: router
spec:
  replicas: {{ .Values.stackstate.components.router.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: router
  strategy:
{{- if eq (lower .Values.stackstate.components.all.deploymentStrategy.type) "recreatesingletonsonly" }}
    type: RollingUpdate
{{- else }}
    {{- toYaml .Values.stackstate.components.all.deploymentStrategy | nindent 4 }}
{{- end }}
  template:
    metadata:
      annotations:
        {{- include "stackstate.router.configmap.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: router
    spec:
      {{- include "stackstate.image.pullSecret.name" (dict "images" (list .Values.stackstate.components.all.image) "context" $) | nindent 6 }}
      containers:
      - {{ toYaml $stsstackstateRouterMainContainer | nindent 8 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "common.fullname.short" . }}-router
          items:
          - key: envoy.yaml
            path: envoy.yaml
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.router.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.router.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.router.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.router.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.router.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.router.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.stackstate.components.all.securityContext.enabled }}
      securityContext: {{- omit .Values.stackstate.components.all.securityContext "enabled" | toYaml | nindent 8 }}
    {{- end }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $routerDeployment := fromYaml (include "stackstate.router.deployment" .) -}}
{{- toYaml (merge $routerDeployment $commonDeployment) -}}
