{{- define "stackstate.receiver.deployment.container.init" -}}
name: receiver-init
command:
- sh
- -c
- |
  /entrypoint -c {{ include "stackstate.kafka.endpoint" . }},{{ include "stackstate.es.endpoint" . }} -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
imagePullPolicy: {{ .Values.stackstate.components.wait.image.pullPolicy | quote }}
{{- end -}}

{{- define "stackstate.receiver.deployment.container.main" -}}
env:
{{- $serviceConfig := dict "ServiceName" "receiver" "ServiceConfig" .Values.stackstate.components.receiver }}
{{- include "stackstate.service.envvars" (merge $serviceConfig .) }}
- name: ELASTICSEARCH_URI
  value: "http://{{ include "stackstate.es.endpoint" . }}"
- name: KAFKA_BROKERS
  value: {{ include "stackstate.kafka.endpoint" . | quote }}
- name: RECEIVER_WRITE_STS_MULTI_METRICS
  value: "{{ not .Values.stackstate.experimental.disableMultimetrics }}"
- name: RECEIVER_WRITE_STS_METRICS
  value: "false"
- name: PROMETHEUS_WRITE_ENDPOINT
  value: http://stackstate-vmagent:8429/api/v1/write
{{ $replicationFactor := ternary "1" "0" (gt .Values.elasticsearch.replicas 2.0) }}
- name: CONFIG_FORCE_stackstate_receiver_k8sLogs_replicas
  value: "{{ $replicationFactor  }}"
{{ $diskSpaceMB := (include "stackstate.storage.to.megabytes" .Values.elasticsearch.volumeClaimTemplate.resources.requests.storage) }}
{{ if $diskSpaceMB  }}
- name: CONFIG_FORCE_stackstate_receiver_elasticsearchDiskSpaceMB
  value: "{{ div (mul (div (mul $diskSpaceMB .Values.elasticsearch.replicas) (add1 $replicationFactor)) .Values.stackstate.components.receiver.esDiskSpaceShare) 100 }}"
{{ end }}
- name: API_KEY
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname.short" . }}-receiver
      key: sts-receiver-api-key
image: "{{ include "stackstate.image.registry" . }}/{{ .Values.stackstate.components.receiver.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ default .Values.stackstate.components.all.image.tag .Values.stackstate.components.receiver.image.tag }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.receiver.image.pullPolicy | quote }}
name: receiver
args:
{{- include "stackstate.service.args" . }}
volumeMounts:
{{- include "stackstate.service.container.volumes" . }}
ports:
- containerPort: 1618
  name: health
- containerPort: 7077
  name: receiver
{{- if .Values.stackstate.components.all.metrics.enabled }}
- containerPort: 9404
  name: metrics
{{- end }}
livenessProbe:
  httpGet:
    path: /liveness
    port: health
  initialDelaySeconds: 60
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /readiness
    port: health
  initialDelaySeconds: 10
  timeoutSeconds: 5
{{- with .Values.stackstate.components.receiver.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}

{{- define "stackstate.receiver.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.receiver.deployment.container.main" .) -}}
{{- $stsstackstateReceiverMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "stackstate.receiver.deployment.container.init" .) -}}
{{- $stsstackstateReceiverInitContainer := (merge $overrideContainer $commonContainer) -}}
metadata:
  name: {{ template "common.fullname.short" . }}-receiver
  labels:
    app.kubernetes.io/component: receiver
spec:
  replicas: {{ .Values.stackstate.components.receiver.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: receiver
  strategy:
{{- if eq (lower .Values.stackstate.components.all.deploymentStrategy.type) "recreatesingletonsonly" }}
    type: RollingUpdate
{{- else }}
    {{- toYaml .Values.stackstate.components.all.deploymentStrategy | nindent 4 }}
{{- end }}
  template:
    metadata:
      annotations:
        {{- include "common.metrics.annotations" (dict "metrics" .Values.stackstate.components.all.metrics "port" "9404" "container_name" "receiver" "filter" .Values.stackstate.components.receiver.agentMetricsFilter) | indent 8 }}
        {{- include "stackstate.common.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.receiver.secret.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: receiver
    spec:
      {{- include "stackstate.image.pullSecret.name" (dict "images" (list .Values.stackstate.components.all.image) "context" $) | nindent 6 }}
      initContainers:
      - {{ toYaml $stsstackstateReceiverInitContainer | nindent 8 }}
      containers:
      - {{ toYaml $stsstackstateReceiverMainContainer | nindent 8 }}
      volumes:
        {{- include "stackstate.service.pod.volumes" (dict "pod_name" "receiver" "root" . ) | nindent 8 }}
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.receiver.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.receiver.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.receiver.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.receiver.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.receiver.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.receiver.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.stackstate.components.all.securityContext.enabled }}
      securityContext: {{- omit .Values.stackstate.components.all.securityContext "enabled" | toYaml | nindent 8 }}
    {{- end }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $receiverDeployment := fromYaml (include "stackstate.receiver.deployment" .) -}}
{{- toYaml (merge $receiverDeployment $commonDeployment) -}}
