{{- if .Values.ingress.enabled -}}
{{- if .Values.opentelemetry.enabled -}}
{{- $serviceName := include "stackstate.otel.http.host" . -}}
{{- $values := (dict "serviceName" $serviceName "port" 4317 "hostPrefix" "otlp-" "global" .) -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "common.fullname.short" . }}-otel
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  {{- $ctx := . }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ print "otlp-" (tpl . $ctx) | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- include "stackstate.ingress.rules" $values | nindent 4 }}
{{- end }}
{{- end }}
