{{- if and .Values.backup.enabled .Values.backup.stackGraph.scheduled.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname.short" . }}-backup-stackgraph-tmp-data
spec:
  accessModes: {{ .Values.backup.stackGraph.scheduled.tempData.accessModes }}
  resources:
    requests:
      storage: {{ tpl .Values.backup.stackGraph.scheduled.tempData.size . }}
{{- if .Values.backup.stackGraph.scheduled.tempData.storageClass }}
  {{- if (eq "-" .Values.backup.stackGraph.scheduled.tempData.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.backup.stackGraph.scheduled.tempData.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
