{{- define "stackstate.checks.persistentvolumeclaim.txLog" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-checks-txlog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stackstate.experimental.storeTransactionLogsToPVC.volumeSize }}
{{- end -}}

{{- if and .Values.stackstate.experimental.storeTransactionLogsToPVC.enabled .Values.stackstate.experimental.server.split }}
{{- $commonPVC := fromYaml (include "common.persistentvolumeclaim" .) -}}
{{- $stackstateChecksPVCTxLog := fromYaml (include "stackstate.checks.persistentvolumeclaim.txLog" .) -}}
{{- toYaml (merge $stackstateChecksPVCTxLog $commonPVC) -}}
{{- end -}}

{{- if and .Values.stackstate.components.checks.tmpToPVC .Values.stackstate.experimental.server.split }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname.short" . }}-checks-tmp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stackstate.components.checks.tmpToPVC.volumeSize }}
  {{ include "common.storage.class" ( dict "persistence" .Values.stackstate.components.checks.tmpToPVC "global" .Values.global) | nindent 2 }}
{{- end}}
