{{- define "stackstate.checks.persistentvolumeclaim.txLog" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-checks-txlog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stackstate.experimental.storeTransactionLogsToPVC.volumeSize }}
{{- end -}}

{{- if .Values.stackstate.experimental.storeTransactionLogsToPVC.enabled }}
{{- $commonPVC := fromYaml (include "common.persistentvolumeclaim" .) -}}
{{- $stackstateChecksPVCTxLog := fromYaml (include "stackstate.checks.persistentvolumeclaim.txLog" .) -}}
{{- toYaml (merge $stackstateChecksPVCTxLog $commonPVC) -}}
{{- end -}}

{{- if and .Values.stackstate.components.checks.tmpToPVC .Values.stackstate.experimental.server.split }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname.short" . }}-checks-tmp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stackstate.components.checks.tmpToPVC.volumeSize }}
  {{- if .Values.stackstate.components.checks.tmpToPVC.storageClassName }}
  storageClassName: {{ .Values.stackstate.components.checks.tmpToPVC.storageClassName | quote }}
  {{- end }}
{{- end}}
