{{- if and .Values.backup.enabled .Values.backup.configuration.scheduled.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname.short" . }}-stackstate-k8s-backup
  labels:
    app.kubernetes.io/component: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stackstate-k8s-backup
subjects:
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-backup
  namespace: {{ .Release.Namespace }}
{{- end -}}
