{{- define "stackstate.clickhouse-backup.service" -}}
apiVersion: {{ .Values.common.service.apiVersion }}
kind: Service
metadata:
  name: suse-observability-clickhouse-backup
  labels:
    app.kubernetes.io/component: clickhouse-backup
spec:
  clusterIP: None
  ports:
    - name: backup-api
      port: 7171
      protocol: TCP
      targetPort: backup-api
  selector:
    app.kubernetes.io/component: clickhouse
    shard: "0"
    statefulset.kubernetes.io/pod-name: "suse-observability-clickhouse-shard0-0"
  type: ClusterIP
{{- end -}}

{{- if and .Values.clickhouse.enabled .Values.clickhouse.backup.enabled }}
{{- include "stackstate.clickhouse-backup.service" . -}}
{{- end -}}
