apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "labels" . | nindent 4 }}
data:
  tenantprovisioning.yaml: |
    ListenAddr: "{{ .Values.config.ListenAddr | required "config.ListenAddr is required" }}"
    TmpDir: "{{ .Values.config.TmpDir | required "config.TmpDir is required" }}"
    Git:
      RepoURL: "{{ .Values.config.Git.RepoURL | required "config.Git.RepoURL is required" }}"
      Branch: "{{ .Values.config.Git.Branch | required "config.Git.Branch is required" }}"
      Auth:
        Username: "{{ .Values.config.Git.Auth.Username | required "config.Git.Auth.Username is required" }}"
      CommitAuthor:
        Name: "{{ .Values.config.Git.CommitAuthor.Name | required "config.Git.CommitAuthor.Name is required" }}"
        Email: "{{ .Values.config.Git.CommitAuthor.Email | required "config.Git.CommitAuthor.Email is required" }}"
      PGPKeyPath: /config/private.key
    Clusters:
{{- range $index, $cluster := .Values.config.Clusters }}
    - Name: "{{ $cluster.Name | required "config.Clusters[$index].Name is required" }}"
      AvailabilityZones:
{{- range $zone := $cluster.AvailabilityZones }}
      - "{{ $zone | required "config.Clusters[$index].AvailabilityZones is required" }}"
{{- end }}
{{- end }}
    AWS:
      Region: "{{ .Values.config.AWS.Region | required "config.AWS.Region is required" }}"
{{- if .Values.config.AWS.SQSBaseEndpoint }}
      SQSBaseEndpoint: "{{ .Values.config.AWS.SQSBaseEndpoint }}"
{{- end }}
      TenantProvisioningQueueURL: "{{ .Values.config.AWS.TenantProvisioningQueueURL | required "config.AWS.TenantProvisioningQueueURL is required" }}"
      TenantProvisioningInternalWorkQueueURL: "{{ .Values.config.AWS.TenantProvisioningInternalWorkQueueURL | required "config.AWS.TenantProvisioningInternalWorkQueueURL is required" }}"
      TenantProvisioningStatusOutputQueueURL: "{{ .Values.config.AWS.TenantProvisioningStatusOutputQueueURL | required "config.AWS.TenantProvisioningStatusOutputQueueURL is required" }}"
    ArgoCD:
      ServerAddr: "{{ .Values.config.ArgoCD.ServerAddr | required "config.ArgoCD.ServerAddr is required" }}"
      Insecure: {{ .Values.config.ArgoCD.Insecure | required "config.ArgoCD.Insecure is required" }}
      GitRepo: {{ .Values.config.ArgoCD.GitRepo | required "config.ArgoCD.GitRepo is required" }}
