---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  TENANTPROVISIONING_GIT_AUTH_PASSWORD: {{ .Values.config.Git.Auth.Password | required "config.Git.Auth.Password is required" | b64enc }}
  TENANTPROVISIONING_GENERIC_WEBHOOK_AUTH_TOKEN: {{ .Values.config.GenericWebhookAuthToken | required "config.GenericWebhookAuthToken is required" | b64enc }}
  TENANTPROVISIONING_ARGOCD_AUTH_TOKEN: {{ .Values.config.ArgoCD.AuthToken | required "config.ArgoCD.AuthToken is required" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-gpg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  private.key: {{ .Values.config.PrivateGPGKeyBase64Encoded | required "config.PrivateGPGKeyBase64Encoded is required" }}
