apiVersion: v1
kind: ServiceAccount
metadata:
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{ include "labels" . | nindent 4 }}
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
