apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-proxy.fullname" . }}-htpasswd
  labels:
    {{- include "gitlab-proxy.labels" . | nindent 4 }}
stringData:
  .htpasswd: {{ .Values.auth.htpasswd | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-proxy.fullname" . }}-server-block
  labels:
    {{- include "gitlab-proxy.labels" . | nindent 4 }}
stringData:
  server-block.conf: {{ .Values.nginx.serverBlock | quote }}
