{{- define "stackstate.e2es.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-e2es-log
data:
  logback.xml: |
{{- $logging := printf "%s\n%s" (include "stackstate.configmap.e2es-base-log" .) .Values.stackstate.components.e2es.additionalLogging -}}
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "INFO" "AdditionalLogging" $logging) .) | nindent 4 -}}
{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateK2ESLogConfigMap := fromYaml (include "stackstate.e2es.configmap-log" .) -}}
{{- toYaml (merge $stackstateK2ESLogConfigMap $commonConfigMap) -}}
