{{- define "stackstate.receiver.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-receiver
{{- include "stackstate.service.configmap.data" (dict "service" .Values.stackstate.components.receiver "context" $) | nindent 0 -}}
{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateReceiverConfigMap := fromYaml (include "stackstate.receiver.configmap" .) -}}
{{- toYaml (merge $stackstateReceiverConfigMap $commonConfigMap) -}}
