{{- define "stackstate.slicing.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-slicing
{{- include "stackstate.service.configmap.data" (dict "service" .Values.stackstate.components.slicing "context" $) | nindent 0 -}}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateSlicingConfigMap := fromYaml (include "stackstate.slicing.configmap" .) -}}
{{- toYaml (merge $stackstateSlicingConfigMap $commonConfigMap) -}}
{{- end -}}
