{{- define "stackstate.sync.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-sync
{{- include "stackstate.service.configmap.data" (dict "service" .Values.stackstate.components.sync "context" $) | nindent 0 -}}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateSyncConfigMap := fromYaml (include "stackstate.sync.configmap" .) -}}
{{- toYaml (merge $stackstateSyncConfigMap $commonConfigMap) -}}
{{- end -}}
