{{- define "stackstate.api.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-api
{{- include "stackstate.service.configmap.data" (dict "service" .Values.stackstate.components.api "context" $) | nindent 0 -}}
{{- include "stackstate.configmap.server-and-api" . | nindent 4 -}}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateApiConfigmap := fromYaml (include "stackstate.api.configmap" .) -}}
{{- toYaml (merge $stackstateApiConfigmap $commonConfigMap) -}}
{{- end -}}
