{{- define "stackstate.router.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-router
data:
  envoy.yaml: |-
    node:
      cluster: suse-observability
      id: suse-observability
    dynamic_resources: # Using dynamic resources to allow enabling/disabling dynamically
      cds_config:
        path_config_source:
          path: /etc/envoy/dynamic/clusters.yaml
          watched_directory:
            path: /etc/envoy/dynamic
      lds_config:
        path_config_source:
          path: /etc/envoy/dynamic/listeners.yaml
          watched_directory:
            path: /etc/envoy/dynamic
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 8001
{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateRouterConfigMap := fromYaml (include "stackstate.router.configmap" .) -}}
{{- toYaml (merge $stackstateRouterConfigMap $commonConfigMap) -}}
