{{- define "stackstate.state.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-state-log
data:
  logback.groovy: |
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "WARN" "AdditionalLogging" .Values.stackstate.components.state.additionalLogging) .) | nindent 4 -}}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateStateLogConfigMap := fromYaml (include "stackstate.state.configmap-log" .) -}}
{{- toYaml (merge $stackstateStateLogConfigMap $commonConfigMap) -}}
{{- end -}}
