{{- define "stackstate.backup.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-backup-log
data:
  logback.groovy: |
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "WARN" "AdditionalLogging" .Values.backup.additionalLogging) .) | nindent 4 -}}
{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateBackupLogConfigMap := fromYaml (include "stackstate.backup.configmap-log" .) -}}
{{- toYaml (merge $stackstateBackupLogConfigMap $commonConfigMap) -}}
