{{- $crdDefinitions := (.Files.Get ("sts-authz-permissions/crd-k8s-authz-permissions-definitions.yaml")) | fromYaml }}
{{- if $crdDefinitions }}

{{- range $crd := $crdDefinitions.definitions }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ $crd.name | replace "_" "" }}.{{ $crdDefinitions.apiGroup }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  names:
    kind: {{ ($crd.singular | camelcase) }}
    singular: {{ $crd.singular | replace "_" "" }}
    plural: {{ $crd.name | replace "_" "" }}
  scope: Namespaced
  group: {{ $crdDefinitions.apiGroup | quote }}
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
---
{{- end }}


{{- else }}
{{- fail (printf "crdDefinitions could not be found") }}
{{- end }}
