{{- if and .Values.backup.enabled (or .Values.backup.stackGraph.restore.enabled .Values.backup.stackGraph.scheduled.enabled .Values.backup.elasticsearch.restore.enabled .Values.backup.elasticsearch.scheduled.enabled (index .Values "victoria-metrics-0" "backup" "enabled") (index .Values "victoria-metrics-1" "backup" "enabled") (index .Values "victoria-metrics-0" "restore" "enabled") (index .Values "victoria-metrics-1" "restore" "enabled") .Values.clickhouse.backup.enabled .Values.clickhouse.restore.enabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-backup-init
  labels:
    app.kubernetes.io/component: backup
    {{- include "suse-observability.labels.global" . | nindent 4 }}
spec:
  schedule: "0 0 31 2 *"
  suspend: true
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup
        {{- include "suse-observability.labels.global" . | nindent 8 }}
    spec:
      {{- include "suse-observability.backup.init.jobSpec" . | nindent 6 }}
{{- end }}
