{{- define "stackstate.sync.deployment.container.init" -}}
name: server-init
{{- if eq .Values.hbase.deployment.mode "Distributed" }}
command:
- sh
- -c
- |
  /entrypoint -c {{ include "stackstate.kafka.endpoint" . }},{{ include "stackgraph.hbase.waitfor" . }},{{ template "common.fullname.short" . }}-initializer:1618 -t 300
{{- else }}
command:
  - sh
  - -c
  - |
    /entrypoint -c {{ include "stackstate.kafka.endpoint" . }},{{- .Release.Name }}-hbase-stackgraph:2182,{{ template "common.fullname.short" . }}-initializer:1618 -t 300
{{- end }}
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
imagePullPolicy: {{ .Values.stackstate.components.wait.image.pullPolicy | quote }}
{{- end -}}

{{- define "stackstate.sync.deployment.container.main" -}}
args:
{{- include "stackstate.service.args" . }}
- -startRole
- sync
envFrom:
  - secretRef:
      name: {{ include "stackstate.secret.name.license" .  }}
env:
{{- $serviceConfig := dict "ServiceName" "sync" "ServiceConfig" .Values.stackstate.components.sync }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.sync.image.tag }}
{{- include "stackstate.service.envvars" (merge $serviceConfig .) }}
{{- include "stackstate.baseurls.envvars" . }}
{{- include "stackstate.metricstore.envvar" . }}
{{- include "stackstate.server.cpu.parallelism" .Values.stackstate.components.sync.resources.requests.cpu }}
- name: CONFIG_FORCE_stackstate_cacheStorage_backend
  value: {{ .Values.stackstate.components.sync.cache.backend }}
{{- if eq (lower .Values.stackstate.components.sync.cache.backend) "rocksdb" }}
{{- $config := dict "Mem" $serviceConfig.ServiceConfig.resources.limits.memory "BaseMem" $serviceConfig.ServiceConfig.sizing.baseMemoryConsumption "JavaHeapFraction" $serviceConfig.ServiceConfig.sizing.javaHeapMemoryFraction }}
- name: CONFIG_FORCE_stackstate_rocksdb_cacheSizeBytes
  value: {{ include "stackstate.server.cache.memory.limit" $config | int | quote }}
{{- end }}
- name: ELASTICSEARCH_URI
  value: "http://{{ include "stackstate.es.endpoint" . }}"
- name: KAFKA_BROKERS
  value: {{ include "stackstate.kafka.endpoint" . | quote }}
- name: PROMETHEUS_WRITE_ENDPOINT
  value: http://{{ include "stackstate.vmagent.endpoint" . }}:8429/api/v1/write
- name: HADOOP_USER_NAME
  value: nobody
- name: ZOOKEEPER_QUORUM
  value: {{ include "stackgraph.zookeeper.endpoint" . | quote }}
  # No need to keep data for a long time, data is very ephemeral.
  # Only stuff that is used often is cached
- name: CONFIG_FORCE_stackgraph_vertex_cache_expireAfterSeconds
  value: "600"
{{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.all.envsFromExistingSecrets }}
{{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.sync.envsFromExistingSecrets }}
image: "{{ include "stackstate.image.registry" (merge $serviceConfig .) }}/{{ .Values.stackstate.components.sync.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.sync.image.pullPolicy | quote }}
name: sync
ports:
- containerPort: 1618
  name: health
{{- if .Values.stackstate.instanceDebugApi.enabled }}
- containerPort: 7080
  name: instance
{{- end }}
{{- if .Values.stackstate.components.all.metrics.enabled }}
- containerPort: 9404
  name: metrics
{{- end }}
livenessProbe:
  httpGet:
    path: /liveness
    port: health
  initialDelaySeconds: 60
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /readiness
    port: health
  initialDelaySeconds: 10
  timeoutSeconds: 5
{{- with .Values.stackstate.components.sync.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
{{- if .Values.stackstate.components.sync.tmpToPVC }}
- name: tmp-volume
  mountPath: /tmp
{{- end}}
{{- include "stackstate.service.container.volumes" . }}
{{- if (include "suse-observability.features.enabled" (dict "key" "storeTransactionLogsToPVC.enabled" "context" .)) }}
{{ include "stackstate.service.transactionLog.volumeMount" . }}
{{- end }}
{{- end -}}

{{- define "stackstate.sync.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.sync.deployment.container.main" .) -}}
{{- $stsStackstateSyncMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "stackstate.sync.deployment.container.init" .) -}}
{{- $stsStackstateServerInitContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "stackstate.initContainer.ensure.no.server.statefulset.pods.are.running" .) -}}
{{- $stsStackstateServerEnsureNoServerStatefulSetPodsAreRunningContainer := (merge $overrideContainer $commonContainer) -}}

metadata:
  name: {{ template "common.fullname.short" . }}-sync
  labels:
    app.kubernetes.io/component: sync
    stackstate.com/connects-to-stackgraph: "true"
    stackstate.com/replicas: "1"
spec:
  replicas: {{ .Values.stackstate.components.sync.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: sync
  strategy:
{{- if eq (lower .Values.stackstate.components.all.deploymentStrategy.type) "recreatesingletonsonly" }}
    type: Recreate
{{- else }}
    {{- toYaml .Values.stackstate.components.all.deploymentStrategy | nindent 4 }}
{{- end }}
  template:
    metadata:
      annotations:
        {{- include "common.metrics.annotations" (dict "metrics" .Values.stackstate.components.all.metrics "port" "9404" "container_name" "sync" "filter" .Values.stackstate.components.sync.agentMetricsFilter) | indent 8 }}
        {{- include "stackstate.common.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.license.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.sync.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.sync.configmap.checksum" . | nindent 8 }}
        {{- include "stackstate.component.podExtraAnnotations" (merge (dict "Name" "sync") .) }}
      labels:
        app.kubernetes.io/component: sync
        stackstate.com/connects-to-stackgraph: "true"
    spec:
      serviceAccountName: {{ template "common.fullname.short" . }}-sync
      {{- include "stackstate.image.pullSecret.name" (dict "context" $) | nindent 6 }}
      initContainers:
      - {{ toYaml $stsStackstateServerInitContainer | nindent 8 }}
      - {{ toYaml $stsStackstateServerEnsureNoServerStatefulSetPodsAreRunningContainer | nindent 8 }}
      {{- if (include "suse-observability.features.enabled" (dict "key" "storeTransactionLogsToPVC.enabled" "context" .)) }}
      - {{ include "stackstate.initContainer.cleanTransactionLogsDirectory" . | nindent 8 }}
      {{- end }}
      {{- if .Values.stackstate.components.sync.tmpToPVC }}
      - {{ include "stackstate.initContainer.cleanTmpDirectory" . | nindent 8 }}
      {{- end }}
      containers:
      - {{ toYaml $stsStackstateSyncMainContainer | nindent 8 }}
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.sync.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.sync.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.sync.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.sync.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.sync.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.sync.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.stackstate.components.all.securityContext.enabled }}
      securityContext: {{- omit .Values.stackstate.components.all.securityContext "enabled" | toYaml | nindent 8 }}
    {{- end }}
      volumes:
        {{- if .Values.stackstate.components.sync.tmpToPVC }}
        - name: tmp-volume
          persistentVolumeClaim:
            claimName: {{ template "common.fullname.short" . }}-sync-tmp
        {{- end}}
        {{- include "stackstate.service.pod.volumes" (dict "pod_name" "sync" "root" . ) | nindent 8 }}
        {{- if (include "suse-observability.features.enabled" (dict "key" "storeTransactionLogsToPVC.enabled" "context" .)) }}
        {{- include "stackstate.service.transactionLog.volume" (dict "pod_name" "sync" "root" . ) | nindent 8 }}
        {{- end }}
{{- end -}}

{{- if include "suse-observability.features.enabled" (dict "key" "server.split" "context" .) }}
{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $syncDeployment := fromYaml (include "stackstate.sync.deployment" .) -}}
{{- toYaml (merge $syncDeployment $commonDeployment) -}}
{{- end}}
