{{- define "stackstate.notification.deployment.container.init" -}}
name: server-init
{{- if eq .Values.hbase.deployment.mode "Distributed" }}
command:
- sh
- -c
- |
  /entrypoint -c {{ include "stackstate.kafka.endpoint" . }},{{ include "stackgraph.hbase.waitfor" . }},{{ template "common.fullname.short" . }}-initializer:1618 -t 300
{{- else }}
command:
  - sh
  - -c
  - |
    /entrypoint -c {{ include "stackstate.kafka.endpoint" . }},{{- .Release.Name }}-hbase-stackgraph:2182,{{ template "common.fullname.short" . }}-initializer:1618 -t 300
{{- end }}
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
imagePullPolicy: {{ .Values.stackstate.components.wait.image.pullPolicy | quote }}
{{- end -}}

{{- define "stackstate.notification.deployment.container.main" -}}
args:
{{- include "stackstate.service.args" . }}
- -startRole
- notification
envFrom:
  - secretRef:
      name: {{ include "stackstate.secret.name.license" .  }}
  {{- if .Values.stackstate.email.enabled }}
  - secretRef:
      name: {{ include "stackstate.secret.name.email" .  }}
  {{- end }}
env:
{{- $serviceConfig := dict "ServiceName" "notification" "ServiceConfig" .Values.stackstate.components.notification }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.notification.image.tag }}
{{- include "stackstate.service.envvars" (merge $serviceConfig .) }}
{{- include "stackstate.baseurls.envvars" . }}
{{- include "stackstate.metricstore.envvar" . }}
- name: KAFKA_BROKERS
  value: {{ include "stackstate.kafka.endpoint" . | quote }}
- name: PROMETHEUS_WRITE_ENDPOINT
  value: http://{{ include "stackstate.vmagent.endpoint" . }}:8429/api/v1/write
- name: HADOOP_USER_NAME
  value: nobody
- name: ZOOKEEPER_QUORUM
  value: {{ include "stackgraph.zookeeper.endpoint" . | quote }}
{{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.all.envsFromExistingSecrets }}
{{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.notification.envsFromExistingSecrets }}
image: "{{ include "stackstate.image.registry" (merge $serviceConfig .) }}/{{ .Values.stackstate.components.notification.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.notification.image.pullPolicy | quote }}
name: notification
ports:
- containerPort: 1618
  name: health
{{- if .Values.stackstate.instanceDebugApi.enabled }}
- containerPort: 7080
  name: instance
{{- end }}
{{- if .Values.stackstate.components.all.metrics.enabled }}
- containerPort: 9404
  name: metrics
{{- end }}
readinessProbe:
  httpGet:
    path: /readiness
    port: health
  initialDelaySeconds: 10
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    path: /liveness
    port: health
  initialDelaySeconds: 60
  timeoutSeconds: 5
{{- with .Values.stackstate.components.notification.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
{{- include "stackstate.service.container.volumes" . }}
{{- if .Values.stackstate.experimental.storeTransactionLogsToPVC.enabled }}
{{ include "stackstate.service.transactionLog.volumeMount" . }}
{{- end }}
{{- end -}}

{{- define "stackstate.notification.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.notification.deployment.container.main" .) -}}
{{- $stsStackstatenotificationMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "stackstate.notification.deployment.container.init" .) -}}
{{- $stsStackstateServerInitContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "stackstate.initContainer.ensure.no.server.statefulset.pods.are.running" .) -}}
{{- $stsStackstateServerEnsureNoServerStatefulSetPodsAreRunningContainer := (merge $overrideContainer $commonContainer) -}}

metadata:
  name: {{ template "common.fullname.short" . }}-notification
  labels:
    app.kubernetes.io/component: notification
    stackstate.com/connects-to-stackgraph: "true"
    stackstate.com/replicas: "1"
spec:
  replicas: {{ .Values.stackstate.components.notification.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: notification
  strategy:
{{- if eq (lower .Values.stackstate.components.all.deploymentStrategy.type) "recreatesingletonsonly" }}
    type: Recreate
{{- else }}
    {{- toYaml .Values.stackstate.components.all.deploymentStrategy | nindent 4 }}
{{- end }}
  template:
    metadata:
      annotations:
        {{- include "common.metrics.annotations" (dict "metrics" .Values.stackstate.components.all.metrics "port" "9404" "container_name" "notification" "filter" .Values.stackstate.components.notification.agentMetricsFilter) | indent 8 }}
        {{- include "stackstate.common.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.license.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.notification.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.notification.configmap.checksum" . | nindent 8 }}
        {{- include "stackstate.component.podExtraAnnotations" (merge (dict "Name" "notification") .) }}
      labels:
        app.kubernetes.io/component: notification
        stackstate.com/connects-to-stackgraph: "true"
    spec:
      serviceAccountName: {{ template "common.fullname.short" . }}-notification
      {{- include "stackstate.image.pullSecret.name" (dict "context" $) | nindent 6 }}
      initContainers:
      - {{ toYaml $stsStackstateServerInitContainer | nindent 8 }}
      - {{ toYaml $stsStackstateServerEnsureNoServerStatefulSetPodsAreRunningContainer | nindent 8 }}
      {{- if .Values.stackstate.experimental.storeTransactionLogsToPVC.enabled }}
      - {{ include "stackstate.initContainer.cleanTransactionLogsDirectory" . | nindent 8 }}
      {{- end }}
      containers:
      - {{ toYaml $stsStackstatenotificationMainContainer | nindent 8 }}
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.state.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.notification.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.notification.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.notification.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.notification.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.notification.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.stackstate.components.all.securityContext.enabled }}
      securityContext: {{- omit .Values.stackstate.components.all.securityContext "enabled" | toYaml | nindent 8 }}
    {{- end }}
      volumes:
        {{- include "stackstate.service.pod.volumes" (dict "pod_name" "notification" "root" . ) | nindent 8 }}
        {{- if .Values.stackstate.experimental.storeTransactionLogsToPVC.enabled }}
        {{- include "stackstate.service.transactionLog.volume" (dict "pod_name" "notification" "root" . ) | nindent 8 }}
        {{- end }}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $notificationDeployment := fromYaml (include "stackstate.notification.deployment" .) -}}
{{- toYaml (merge $notificationDeployment $commonDeployment) -}}
{{- end}}
