{{- define "stackstate.pull.secret" -}}
  {{- $registryAuthDocument := dict -}}
  {{- $_ := set $registryAuthDocument "username" .username }}
  {{- $_ := set $registryAuthDocument "password" .password }}
  {{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
  {{- $_ := set $registryAuthDocument "auth" $authMessage }}
  {{- $registryAuthMap := dict .registry $registryAuthDocument }}
  {{- $dockerAuthsDocuments := dict "auths" $registryAuthMap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname.short" .context }}-pull-secret
data:
  .dockerconfigjson: {{ $dockerAuthsDocuments | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}

{{- if.Values.stackstate.components.all.image.pullSecretUsername }}
  {{ template "stackstate.pull.secret" (dict "username" .Values.stackstate.components.all.image.pullSecretUsername "password" .Values.stackstate.components.all.image.pullSecretPassword "registry" (include "stackstate.image.registry" $) "context" $) }}
{{- end }}
