apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname.short" . }}-get-pods
roleRef:
  kind: Role
  name: {{ template "common.fullname.short" . }}-get-pods
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- if .Values.stackstate.experimental.server.split }}
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-api
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-authorization-sync
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-checks
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-initializer
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-slicing
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-state
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-sync
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-notification
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-health-sync
{{- else }}
- kind: ServiceAccount
  name: {{ template "common.fullname.short" . }}-server
{{- end -}}
