{{- if index .Values "kubernetes-rbac-agent" "enabled" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname.short" . }}-rbac-agent
roleRef:
  kind: Role
  name: {{ template "stackstate.rbacAgent.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "kubernetes-rbac-agent.serviceaccount.name" . }}
{{- end }}
