{{- if eq .Values.stackstate.components.router.mode.status "automatic" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.fullname.short" . }}-router-mode-scripts
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.deployment.compatibleWithArgoCD }}
    argocd.argoproj.io/hook: PreSync,PostSync,PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-2"
    {{- else }}
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade,post-delete
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
  labels:
    app.kubernetes.io/component: router-mode
  {{- end }}
