apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stackstate-agent.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: agent
{{- with .Values.agent.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
