{{- if and .Values.clusterChecks.enabled .Values.clusterChecks.config.override }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-checks-agent
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: checks-agent
data:
{{- range .Values.clusterChecks.config.override }}
  {{ .path | replace "/" "_"}}_{{ .name }}: |
{{ .data | indent 4 -}}
{{- end -}}
{{- end -}}
