apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cluster-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: cluster-agent
spec:
  ports:
  - name: clusteragent
    port: 5005
    protocol: TCP
    targetPort: {{int .Values.clusterAgent.service.targetPort }}
  selector:
    app.kubernetes.io/component: cluster-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "stackstate-agent.name" . }}
