apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-node-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: node-agent
{{- with .Values.nodeAgent.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
