apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: node-agent
{{- with .Values.agent.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.agent.service.type }}
{{- if eq .Values.agent.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ toYaml .Values.agent.service.loadBalancerSourceRanges | nindent 4}}
{{- end }}
  ports:
  - name: traceport
    port: 8126
    protocol: TCP
    targetPort: 8126
  selector:
    app.kubernetes.io/component: node-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "stackstate-agent.name" . }}
