{{- $kubeStateOverridden := (include "stackstate-agent.nodeAgent.kube-state-metrics.overridden" $) }}
{{- $checksAgentKSM := and (and .Values.checksAgent.enabled (or .Values.dependencies.kubeStateMetrics.enabled .Values.checksAgent.kubeStateMetrics.url)) (not $kubeStateOverridden) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-node-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: node-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: node-agent
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "stackstate-agent.name" . }}
{{- with .Values.nodeAgent.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
  template:
    metadata:
      annotations:
        {{- include "stackstate-agent.checksum-configs" . | nindent 8 }}
        {{- include "stackstate-agent.nodeAgent.configmap.override.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: node-agent
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "stackstate-agent.name" . }}
    spec:
      {{- include "stackstate-agent.image.pullSecret.name" (dict "images" (list .Values.nodeAgent.containers.agent.image) "context" $) | nindent 6 }}
      containers:
        {{- include "container-agent" . | nindent 6 }}
        {{- if .Values.nodeAgent.containers.processAgent.enabled }}
          {{- include "container-process-agent" . | nindent 6 }}
        {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      {{- if .Values.nodeAgent.priorityClassName }}
      priorityClassName: {{ .Values.nodeAgent.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-node-agent
    {{- with .Values.nodeAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.nodeAgent.containerRuntime.customSocketPath }}
      - hostPath:
          path: {{- .Values.nodeAgent.containerRuntime.customSocketPath }}
        name: customcrisocket
      {{- end }}
      - hostPath:
          path: /var/run/crio/crio.sock
        name: crisocket
      - hostPath:
          path: /var/run/containerd/containerd.sock
        name: containerdsocket
      - hostPath:
          path: /sys/kernel/debug
        name: sys-kernel-debug
      - hostPath:
          path: /var/run/docker.sock
        name: dockersocket
      - hostPath:
          path: /proc
        name: procdir
      - hostPath:
          path: /etc/passwd
        name: passwd
      - hostPath:
          path: /sys/fs/cgroup
        name: cgroups
      {{- if or .Values.nodeAgent.config.override $checksAgentKSM }}
      - name: config-override-volume
        configMap:
          name: {{ .Release.Name }}-node-agent
      {{- end }}
