{{- if .Values.openShiftLogging.installSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate-agent.fullname" . }}-logging-secret
  namespace: openshift-logging
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
type: Opaque
data:
  username: {{ "apikey" | b64enc | quote }}
{{- if .Values.global.receiverApiKey }}
  password: {{ .Values.global.receiverApiKey | b64enc | quote }}
{{- else }}
  password: {{ .Values.stackstate.apiKey | b64enc | quote }}
{{- end }}
{{- end }}
