{{- $kubeRes := .Values.stackstateAgent.collection.kubernetesResources }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stackstate-agent.fullname" . }}
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: stackstate-agent
rules:
- apiGroups:
  - ""
  resources:
  - events
  - nodes
  - pods
  - services
  {{- if $kubeRes.namespaces }}
  - namespaces
  {{- end }}
  {{- if .Values.stackstateAgent.collection.kubernetesMetrics }}
  - componentstatuses
  {{- end }}
  {{- if $kubeRes.configmaps }}
  - configmaps
  {{- end }}
  {{- if $kubeRes.endpoints }}
  - endpoints
  {{- end }}
  {{- if $kubeRes.persistentvolumeclaims }}
  - persistentvolumeclaims
  {{- end }}
  {{- if $kubeRes.persistentvolumes }}
  - persistentvolumes
  {{- end }}
  {{- if $kubeRes.secrets }}
  - secrets
  {{- end }}
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - patch
  - update
{{- if or $kubeRes.daemonsets $kubeRes.deployments $kubeRes.replicasets $kubeRes.statefulsets }}
- apiGroups:
  - "apps"
  resources:
  {{- if $kubeRes.daemonsets }}
  - daemonsets
  {{- end }}
  {{- if $kubeRes.deployments }}
  - deployments
  {{- end }}
  {{- if $kubeRes.replicasets }}
  - replicasets
  {{- end }}
  {{- if $kubeRes.statefulsets }}
  - statefulsets
  {{- end }}
  verbs:
  - get
  - list
  - watch
{{- end}}
{{- if $kubeRes.ingresses }}
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
{{- end}}
{{- if or $kubeRes.cronjobs $kubeRes.jobs }}
- apiGroups:
  - "batch"
  resources:
  {{- if $kubeRes.cronjobs }}
  - cronjobs
  {{- end }}
  {{- if $kubeRes.jobs }}
  - jobs
  {{- end }}
  verbs:
  - get
  - list
  - watch
{{- end}}
- nonResourceURLs:
  - "/healthz"
  - "/version"
  verbs:
  - get
