name: Main

on:
  push:
    tags:
      - "suse-observability/*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create backup scripts zip file
        run: |
          tar czf backup-scripts-${GITHUB_REF_NAME#suse-observability/}.tar.gz -C stable/suse-observability/restore .
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }}
          echo 'Uploading helm chart scripts:'
          ls  backup-scripts-*.tar.gz
          gh release upload ${{ github.ref_name }} backup-scripts-*.tar.gz
